apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: tanzuns1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 190Gi
  storageClassName: tanzu
  volumeMode: Filesystem
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  labels:
    vm-selector: minio-vm
  name: minio-vm
  namespace: tanzuns1
spec:
  imageName: centos-stream-8-vmservice-v1alpha1-1619529007339
  className: best-effort-medium
  powerState: poweredOn
  storageClass: tanzu
  networkInterfaces:
  - networkType: nsx-t
    networkName: ""
  volumes:
  - name: minio-vol
    persistentVolumeClaim:
      claimName: minio-pvc
  readinessProbe:
    tcpSocket:
      port: 22
  vmMetadata:
    configMapName: minio-cloudinit
    transport: OvfEnv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cloudinit
  namespace: tanzuns1
data:
  user-data: I2Nsb3VkLWNvbmZpZwpjaHBhc3N3ZDoKICAgIGxpc3Q6IHwKICAgICAgY2VudG9zOlZNd2FyZTEhCiAgICBleHBpcmU6IGZhbHNlCmdyb3VwczoKICAtIGRvY2tlcgp1c2VyczoKICAtIGRlZmF1bHQKICAtIG5hbWU6IGNlbnRvcwogICAgc3NoLWF1dGhvcml6ZWQta2V5czoKICAgICAgLSBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJnUURQNys3NzlpdW1DeHJlTjYxUEtjb3RjNk90MmpRMHViTlRkek5QRFRSNGpQZUJabmhxWDBwc2s0SmpxSlJsNUdEZEQ3ZFByLzNDZHdXeElPU00xZWg3ckRmZGdCZXh5dW1xYWVyV0haYlF4cksyQXpxWDBTNVRWSWtyZEJmWU9hOEI0UkdMYXEzejY2OE5YeGRIVFNyWHozUFdaUWpzSDdobFNROWRkZU14Nlc3OVB6Y3VucEtJbDRwV1pXNnJFNFlhbHdWVjlPbDZvVGRnTDZEaVAzdG53alpiK3AwNEhZelFuQVVKUndqS25QUnI0QWVZY1hYTWY4Z2NWSmZkYUlaTEFhcC92Vm11LzNUazBDVWh3VDYvNkNtRjk3K1QrbysyOW0yd3dFbUt3Nml1WmtEVkpIeGVSdFp1WEI2UHVmVVpWU2ZQT0V5UTJVZ2FuemdsNU8waWtFTmx1cEI0bUU3ellEc2V1TVlWVEtDY04yc1JMMWUraVFvb2JZRm4zbTVLNTFHM292dkMyREVQQ044dlpwNm11ZHhRTktLSW94RG1BN25aQTlvbisxY2F0aWJvMXA2VFhDL2t1dFpaejdVVGVqZlhtWldWWlVadGVmSit6NDZUUFM3aXhxaDJOQVZXbXozcWs4aS9la0Q2bGVlWEhzKzk1QmYrOXNaSmJ1Yz0gZ29ya2VtQGdvcmtlbW8tYTAxLnZtd2FyZS5jb20KICAgIHN1ZG86IEFMTD0oQUxMKSBOT1BBU1NXRDpBTEwKICAgIGdyb3Vwczogc3VkbywgZG9ja2VyCiAgICBzaGVsbDogL2Jpbi9iYXNoCm5ldHdvcms6CiAgdmVyc2lvbjogMgogIGV0aGVybmV0czoKICAgICAgZW5zMTkyOgogICAgICAgICAgZGhjcDQ6IHRydWUKcGFja2FnZV91cGRhdGU6IHRydWUKeXVtX3JlcG9zOgogIGRvY2tlci1jZS1zdGFibGU6CiAgICBuYW1lOiBEb2NrZXIgQ0UgU3RhYmxlIC0gJGJhc2VhcmNoCiAgICBiYXNldXJsOiBodHRwczovL2Rvd25sb2FkLmRvY2tlci5jb20vbGludXgvY2VudG9zLyRyZWxlYXNldmVyLyRiYXNlYXJjaC9zdGFibGUKICAgIGVuYWJsZWQ6IHRydWUKICAgIGdwZ2NoZWNrOiB0cnVlCiAgICBncGdrZXk6IGh0dHBzOi8vZG93bmxvYWQuZG9ja2VyLmNvbS9saW51eC9jZW50b3MvZ3BnCm1vdW50czoKICAtIFsgL2Rldi9zZGIxLCAvZGF0YSwgInhmcyIsICJkZWZhdWx0cyIsICIwIiwgIjIiIF0KcGFja2FnZXM6CiAgLSBuZXQtdG9vbHMKICAtIHdnZXQKd3JpdGVfZmlsZXM6CiAgLSBwYXRoOiAvb3B0L21pbmlvL21pbmlvLmNvbmYKICAgIGNvbnRlbnQ6IHwKICAgICAgTUlOSU9fVk9MVU1FUz0vZGF0YS9taW5pby9kYXRhCiAgICAgIE1JTklPX1JPT1RfVVNFUj1taW5pbwogICAgICBNSU5JT19ST09UX1BBU1NXT1JEPW1pbmlvMTIzCiAgICBvd25lcjogJ3Jvb3Q6cm9vdCcKICAgIHBlcm1pc3Npb25zOiAnMDQ0NCcKICAtIHBhdGg6IC9ldGMvc3lzdGVtZC9zeXN0ZW0vbWluaW8uc2VydmljZQogICAgY29udGVudDogfAogICAgICBbVW5pdF0KICAgICAgRGVzY3JpcHRpb249TWluaW8KICAgICAgRG9jdW1lbnRhdGlvbj1odHRwczovL2RvY3MubWluaW8uaW8KICAgICAgV2FudHM9bmV0d29yay1vbmxpbmUudGFyZ2V0CiAgICAgIEFmdGVyPW5ldHdvcmstb25saW5lLnRhcmdldAogICAgICBBc3NlcnRGaWxlSXNFeGVjdXRhYmxlPS9vcHQvbWluaW8vYmluL21pbmlvCiAgICAgIAogICAgICBbU2VydmljZV0KICAgICAgV29ya2luZ0RpcmVjdG9yeT0vb3B0L21pbmlvCiAgICAgIAogICAgICBVc2VyPXJvb3QKICAgICAgR3JvdXA9d2hlZWwKICAgICAgCiAgICAgIFBlcm1pc3Npb25zU3RhcnRPbmx5PXRydWUKICAgICAgCiAgICAgIEVudmlyb25tZW50RmlsZT0tL29wdC9taW5pby9taW5pby5jb25mCiAgICAgIEV4ZWNTdGFydFByZT0vYmluL2Jhc2ggLWMgIlsgLW4gXCIke01JTklPX1ZPTFVNRVN9XCIgXSB8fCBlY2hvIFwiVmFyaWFibGUgTUlOSU9fVk9MVU1FUyBub3Qgc2V0IGluIC9vcHQvbWluaW8vbWluaW8uY29uZlwiIgogICAgICAKICAgICAgRXhlY1N0YXJ0PS9vcHQvbWluaW8vYmluL21pbmlvIHNlcnZlciAkTUlOSU9fT1BUUyAtLWFkZHJlc3MgMC4wLjAuMDo5MDAwIC0tY29uc29sZS1hZGRyZXNzIDAuMC4wLjA6OTAwMSAkTUlOSU9fVk9MVU1FUwogICAgICAKICAgICAgU3RhbmRhcmRPdXRwdXQ9am91cm5hbAogICAgICBTdGFuZGFyZEVycm9yPWluaGVyaXQKICAgICAgCiAgICAgICMgU3BlY2lmaWVzIHRoZSBtYXhpbXVtIGZpbGUgZGVzY3JpcHRvciBudW1iZXIgdGhhdCBjYW4gYmUgb3BlbmVkIGJ5IHRoaXMgcHJvY2VzcwogICAgICBMaW1pdE5PRklMRT02NTUzNgogICAgICAKICAgICAgIyBEaXNhYmxlIHRpbWVvdXQgbG9naWMgYW5kIHdhaXQgdW50aWwgcHJvY2VzcyBpcyBzdG9wcGVkCiAgICAgIFRpbWVvdXRTdG9wU2VjPTAKICAgICAgCiAgICAgICMgU0lHVEVSTSBzaWduYWwgaXMgdXNlZCB0byBzdG9wIE1pbmlvCiAgICAgIEtpbGxTaWduYWw9U0lHVEVSTQogICAgICAKICAgICAgU2VuZFNJR0tJTEw9bm8KICAgICAgCiAgICAgIFN1Y2Nlc3NFeGl0U3RhdHVzPTAKICAgICAgCiAgICAgIFtJbnN0YWxsXQogICAgICBXYW50ZWRCeT1tdWx0aS11c2VyLnRhcmdldAogICAgb3duZXI6IHJvb3Q6cm9vdAogICAgcGVybWlzc2lvbnM6ICcwNjQ0JwpydW5jbWQ6CiAgLSBwYXJ0ZWQgL2Rldi9zZGIgbWtsYWJlbCBncHQKICAtIHBhcnRlZCAvZGV2L3NkYiBta3BhcnQgcHJpbWFyeSB4ZnMgMU1CIDE5NDU2ME1CCiAgLSAvc2Jpbi9ta2ZzLnhmcyAvZGV2L3NkYjEKICAtIG1rZGlyIC1wIC9kYXRhCiAgLSBtb3VudCAtdCB4ZnMgLS1ydyAvZGV2L3NkYjEgL2RhdGEKICAtIG1rZGlyIC1wIC9vcHQvbWluaW8vYmluCiAgLSBta2RpciAtcCAvZGF0YS9taW5pby9kYXRhCiAgLSB3Z2V0IC1xIGh0dHBzOi8vZGwubWluaW8uaW8vc2VydmVyL21pbmlvL3JlbGVhc2UvbGludXgtYW1kNjQvbWluaW8gLU8gL29wdC9taW5pby9iaW4vbWluaW8KICAtIGNobW9kICt4IC9vcHQvbWluaW8vYmluL21pbmlvCiAgLSBzeXN0ZW1jdGwgZGFlbW9uLXJlbG9hZAogIC0gc3lzdGVtY3RsIGVuYWJsZSBtaW5pbwogIC0gc3lzdGVtY3RsIHN0YXJ0IG1pbmlvCiAgLSBzeXN0ZW1jdGwgc3RvcCBmaXJld2FsbGQKICAtIHN5c3RlbWN0bCBkaXNhYmxlIGZpcmV3YWxsZAoK
  hostname: minio-vm
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineService
metadata:
  name: minio-svc
  namespace: tanzuns1
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: secure
    port: 443
    protocol: TCP
    targetPort: 443
  - name: minio
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: console
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    vm-selector: minio-vm
  type: LoadBalancer
