apiVersion: run.tanzu.vmware.com/v1alpha1      #TKGS API endpoint
kind: TanzuKubernetesCluster                   #required parameter
metadata:
  name: tkgs-cluster-9                         #cluster name, user defined
  namespace: tanzuns1                   #vsphere namespace
spec:
  distribution:
    version: v1.21                             #Resolves to latest TKR 1.21
  topology:
    controlPlane:
      count: 1                                 #number of control plane nodes
      class: best-effort-medium               #vmclass for control plane nodes
      storageClass: tanzu         #storageclass for control plane
    workers:
      count: 3                                 #number of worker nodes
      class: best-effort-2xlarge                #vmclass for worker nodes
      storageClass: tanzu        #storageclass for worker nodes
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 66Gi
  settings:
    storage:
      classes: ["tanzu"]
      defaultClass: tanzu
